import type {
  AgentPermissionGrantDetailContract,
  AgentPermissionGrantSummaryContract,
  AgentPermissionLineageContract,
  AuthorityActivationDetailContract,
  AuthorityActivationHistoryContract,
  AuthorityActivationLineageContract,
  AuthorityActivationSummaryContract,
  DelegatedAuthorityGrantDetailContract,
  DelegatedAuthorityGrantSummaryContract,
  DelegationLineageContract,
  GetAgentPermissionGrantDetailResponse,
  GetAgentPermissionLineageResponse,
  GetAuthorityActivationDetailResponse,
  GetAuthorityActivationHistoryResponse,
  GetAuthorityActivationLineageResponse,
  GetDelegatedAuthorityGrantDetailResponse,
  GetDelegatedAuthorityLineageResponse,
  GetPreparedEffectLineageResponse,
  GetPreparedEffectRequestDetailResponse,
  GetReformAdoptionDecisionDetailResponse,
  ListAgentPermissionGrantsResponse,
  ListAuthorityActivationsResponse,
  ListDelegatedAuthorityGrantsResponse,
  ListPreparedEffectRequestsResponse,
  ListReformAdoptionDecisionsResponse,
  PreparedEffectLineageContract,
  PreparedEffectRequestDetailContract,
  PreparedEffectRequestListItemContract,
  ReformAdoptionDecisionContract,
  StrategyMutationReceiptGroupContract,
} from "@/lib/contracts/collective-observability";
import type { ReformAdoptionFilterState } from "./dto";

const adoptionDecisions: ReformAdoptionDecisionContract[] = [
  {
    decisionId: "adoption-decision-001",
    proposalId: "proposal-signal-weighting-v2",
    legitimacyAssessmentId: "legitimacy-001",
    anchorEpochId: "epoch-2026-q1",
    disposition: "Approved",
    status: "ApprovedForAdoption",
    decisionRationale: "Legitimacy findings support adoption while preserving read-only constitutional posture.",
    governanceContext: {
      authority: "CollectiveCouncil",
      governanceBindingRef: "policy.collective.reform-adoption",
      policyScope: "policy.collective.reform-adoption",
      policyVersion: "2.0.0",
    },
    anchorReceiptRefs: ["receipt:reform-adoption:001", "receipt:legitimacy:001"],
    lineageRefs: ["lineage:proposal:signal-weighting-v2", "lineage:epoch:2026-q1"],
    correlationId: "corr-adoption-001",
    decidedAtUtc: "2026-03-17T10:15:00Z",
    badges: ["read-only", "receipt-backed", "lineage-anchored", "governance-controlled"],
    readOnly: true,
    receiptAnchored: true,
  },
  {
    decisionId: "adoption-decision-002",
    proposalId: "proposal-threshold-policy",
    legitimacyAssessmentId: "legitimacy-002",
    anchorEpochId: "epoch-2026-q1",
    disposition: "Rejected",
    status: "Rejected",
    decisionRationale: "Alternative coverage remained insufficient, so the proposal was constitutionally rejected.",
    governanceContext: {
      authority: "CollectiveCouncil",
      governanceBindingRef: "policy.collective.reform-adoption",
      policyScope: "policy.collective.reform-adoption",
      policyVersion: "2.0.0",
    },
    anchorReceiptRefs: ["receipt:reform-adoption:002", "receipt:legitimacy:002"],
    lineageRefs: ["lineage:proposal:threshold-policy", "lineage:epoch:2026-q1"],
    correlationId: "corr-adoption-002",
    decidedAtUtc: "2026-03-17T12:30:00Z",
    badges: ["read-only", "receipt-backed", "lineage-anchored", "governance-controlled"],
    readOnly: true,
    receiptAnchored: true,
  },
];

const mutationReceiptsByDecision = new Map<string, StrategyMutationReceiptGroupContract[]>([
  [
    "adoption-decision-001",
    [{
      decisionId: "adoption-decision-001",
      receipts: [{
        receiptId: "strategy-mutation-001",
        canonicalReceiptRef: "receipt:strategy-mutation:001",
        adoptionReceiptId: "adoption-receipt-001",
        adoptionDecisionId: "adoption-decision-001",
        anchorEpochId: "epoch-2026-q1",
        operation: "Activate",
        governanceContext: {
          authority: "CollectiveCouncil",
          governanceBindingRef: "policy.collective.strategy-mutation",
          policyScope: "policy.collective.strategy-mutation",
          policyVersion: "1.0.0",
        },
        correlationId: "corr-strategy-001",
        anchorReceiptRefs: ["receipt:strategy-mutation:001", "receipt:reform-adoption:001"],
        lineageRefs: ["lineage:strategy:signal-weighting-v2", "lineage:proposal:signal-weighting-v2"],
        transitionOutcome: { transition: "activated" },
        recordedAtUtc: "2026-03-17T10:20:00Z",
        canonical: true,
        readOnly: true,
      }],
    }],
  ],
]);

const delegationSummaries: DelegatedAuthorityGrantSummaryContract[] = [
  {
    grantId: "delegation-grant-001",
    delegatorAuthorityRef: "CollectiveCouncil",
    delegateActorId: "actor-governance-steward",
    tenantId: "tenant-keon",
    governanceBindingRef: "policy.collective.delegation",
    canonicalStatus: "Active",
    status: "Active",
    correlationId: "corr-delegation-001",
    anchorReceiptRefs: ["receipt:delegation:001"],
    lineageRefs: ["lineage:delegation:001", "lineage:epoch:2026-q1"],
    effectiveFromUtc: "2026-03-17T09:00:00Z",
    expiresAtUtc: "2026-06-01T00:00:00Z",
    badges: ["read-only", "receipt-anchored", "lineage-preserved", "delegation-record"],
    readOnly: true,
    receiptAnchored: true,
  },
  {
    grantId: "delegation-grant-002",
    delegatorAuthorityRef: "CollectiveCouncil",
    delegateActorId: "actor-policy-auditor",
    tenantId: "tenant-keon",
    governanceBindingRef: "policy.collective.delegation",
    canonicalStatus: "Revoked",
    status: "Revoked",
    correlationId: "corr-delegation-002",
    anchorReceiptRefs: ["receipt:delegation:002"],
    lineageRefs: ["lineage:delegation:002", "lineage:epoch:2026-q1"],
    effectiveFromUtc: "2026-03-10T09:00:00Z",
    expiresAtUtc: "2026-04-01T00:00:00Z",
    badges: ["read-only", "receipt-anchored", "lineage-preserved", "delegation-record"],
    readOnly: true,
    receiptAnchored: true,
  },
];

const delegationDetails = new Map<string, DelegatedAuthorityGrantDetailContract>([
  ["delegation-grant-001", {
    summary: delegationSummaries[0],
    delegateEntityId: "entity-governance-steward",
    domainScope: "collective.reform",
    policyScope: "policy.collective.delegation",
    policyVersion: "3.1.0",
    authorityClass: "CollectiveAuthority",
    effectClass: "ReformObservation",
    upstreamAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective",
      policyScope: "policy.collective",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "ReformObservation",
    },
    constraintStatements: ["ScopeMayOnlyNarrow=true", "AllowsReDelegation=false"],
    issuedAtUtc: "2026-03-17T08:30:00Z",
    revocation: null,
    upstreamGrantId: null,
  }],
  ["delegation-grant-002", {
    summary: delegationSummaries[1],
    delegateEntityId: null,
    domainScope: "collective.audit",
    policyScope: "policy.collective.delegation",
    policyVersion: "3.1.0",
    authorityClass: "CollectiveAuthority",
    effectClass: "AuditObservation",
    upstreamAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective",
      policyScope: "policy.collective",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "AuditObservation",
    },
    constraintStatements: ["ScopeMayOnlyNarrow=true"],
    issuedAtUtc: "2026-03-10T08:45:00Z",
    revocation: {
      revocationId: "delegation-revocation-002",
      grantId: "delegation-grant-002",
      revokedByActorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.delegation",
      revocationReason: "Oversight review revoked the grant after policy scope drift.",
      correlationId: "corr-delegation-002",
      anchorReceiptRefs: ["receipt:delegation-revocation:002"],
      lineageRefs: ["lineage:delegation:002", "lineage:revocation:002"],
      revokedAtUtc: "2026-03-15T14:00:00Z",
    },
    upstreamGrantId: null,
  }],
]);

const delegationLineages = new Map<string, DelegationLineageContract>([
  ["delegation-grant-001", {
    grantId: "delegation-grant-001",
    governanceBindingRef: "policy.collective.delegation",
    correlationId: "corr-delegation-001",
    lineageRefs: ["lineage:delegation:001", "lineage:epoch:2026-q1"],
    anchorReceiptRefs: ["receipt:delegation:001"],
    upstreamGrantId: null,
    canonicalStatus: "Active",
    history: [{
      transitionId: "delegation-transition-001",
      grantId: "delegation-grant-001",
      fromStatus: "Draft",
      toStatus: "Active",
      actorId: "actor-collective-council",
      governanceBindingRef: "policy.collective.delegation",
      reason: "Approved for constrained observation coverage.",
      anchorReceiptRefs: ["receipt:delegation:001"],
      lineageRefs: ["lineage:delegation:001"],
      transitionedAtUtc: "2026-03-17T09:00:00Z",
    }],
    readOnly: true,
  }],
  ["delegation-grant-002", {
    grantId: "delegation-grant-002",
    governanceBindingRef: "policy.collective.delegation",
    correlationId: "corr-delegation-002",
    lineageRefs: ["lineage:delegation:002", "lineage:epoch:2026-q1"],
    anchorReceiptRefs: ["receipt:delegation:002"],
    upstreamGrantId: null,
    canonicalStatus: "Revoked",
    history: [{
      transitionId: "delegation-transition-002",
      grantId: "delegation-grant-002",
      fromStatus: "Proposed",
      toStatus: "Revoked",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.delegation",
      reason: "Revoked after scope drift.",
      anchorReceiptRefs: ["receipt:delegation-revocation:002"],
      lineageRefs: ["lineage:delegation:002", "lineage:revocation:002"],
      transitionedAtUtc: "2026-03-15T14:00:00Z",
    }],
    readOnly: true,
  }],
]);

const permissionSummaries: AgentPermissionGrantSummaryContract[] = [
  {
    grantId: "permission-grant-001",
    grantingAuthorityRef: "actor-governance-steward",
    agentId: "agent-omega",
    tenantId: "tenant-keon",
    delegationGrantId: "delegation-grant-001",
    governanceBindingRef: "policy.collective.permission",
    canonicalStatus: "Active",
    status: "Active",
    correlationId: "corr-permission-001",
    anchorReceiptRefs: ["receipt:permission:001"],
    lineageRefs: ["lineage:permission:001", "lineage:delegation:001"],
    effectiveFromUtc: "2026-03-17T09:05:00Z",
    expiresAtUtc: "2026-05-01T00:00:00Z",
    badges: ["read-only", "receipt-anchored", "lineage-preserved", "permission-record"],
    readOnly: true,
    receiptAnchored: true,
  },
  {
    grantId: "permission-grant-002",
    grantingAuthorityRef: "actor-governance-steward",
    agentId: "agent-sandbox",
    tenantId: "tenant-keon",
    delegationGrantId: "delegation-grant-002",
    governanceBindingRef: "policy.collective.permission",
    canonicalStatus: "Rejected",
    status: "Rejected",
    correlationId: "corr-permission-002",
    anchorReceiptRefs: ["receipt:permission:002"],
    lineageRefs: ["lineage:permission:002", "lineage:delegation:002"],
    effectiveFromUtc: "2026-03-12T09:05:00Z",
    expiresAtUtc: "2026-04-01T00:00:00Z",
    badges: ["read-only", "receipt-anchored", "lineage-preserved", "permission-record"],
    readOnly: true,
    receiptAnchored: true,
  },
];

const permissionDetails = new Map<string, AgentPermissionGrantDetailContract>([
  ["permission-grant-001", {
    summary: permissionSummaries[0],
    agentEntityId: "entity-agent-omega",
    domainScope: "collective.reform",
    policyScope: "policy.collective.permission",
    policyVersion: "3.1.0",
    authorityClass: "CollectiveAuthority",
    effectClass: "ReformObservation",
    actionCategories: ["read.reform"],
    capabilityCategories: ["observe.reform"],
    delegatedAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.reform",
      policyScope: "policy.collective.delegation",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "ReformObservation",
    },
    constraintStatements: ["ScopeMayOnlyNarrow=true", "Categories are explicit subsets"],
    issuedAtUtc: "2026-03-17T09:02:00Z",
    revocation: null,
  }],
  ["permission-grant-002", {
    summary: permissionSummaries[1],
    agentEntityId: null,
    domainScope: "collective.audit",
    policyScope: "policy.collective.permission",
    policyVersion: "3.1.0",
    authorityClass: "CollectiveAuthority",
    effectClass: "AuditObservation",
    actionCategories: ["read.audit"],
    capabilityCategories: ["observe.audit"],
    delegatedAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.audit",
      policyScope: "policy.collective.delegation",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "AuditObservation",
    },
    constraintStatements: ["Rejected during governance review"],
    issuedAtUtc: "2026-03-12T09:00:00Z",
    revocation: null,
  }],
]);

const permissionLineages = new Map<string, AgentPermissionLineageContract>([
  ["permission-grant-001", {
    grantId: "permission-grant-001",
    delegationGrantId: "delegation-grant-001",
    governanceBindingRef: "policy.collective.permission",
    correlationId: "corr-permission-001",
    lineageRefs: ["lineage:permission:001", "lineage:delegation:001"],
    anchorReceiptRefs: ["receipt:permission:001"],
    canonicalStatus: "Active",
    history: [{
      transitionId: "permission-transition-001",
      grantId: "permission-grant-001",
      fromStatus: "Draft",
      toStatus: "Active",
      actorId: "actor-governance-steward",
      governanceBindingRef: "policy.collective.permission",
      reason: "Delegated authority narrowed into an explicit observation permission.",
      anchorReceiptRefs: ["receipt:permission:001"],
      lineageRefs: ["lineage:permission:001", "lineage:delegation:001"],
      transitionedAtUtc: "2026-03-17T09:05:00Z",
    }],
    readOnly: true,
  }],
  ["permission-grant-002", {
    grantId: "permission-grant-002",
    delegationGrantId: "delegation-grant-002",
    governanceBindingRef: "policy.collective.permission",
    correlationId: "corr-permission-002",
    lineageRefs: ["lineage:permission:002", "lineage:delegation:002"],
    anchorReceiptRefs: ["receipt:permission:002"],
    canonicalStatus: "Rejected",
    history: [{
      transitionId: "permission-transition-002",
      grantId: "permission-grant-002",
      fromStatus: "Draft",
      toStatus: "Rejected",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.permission",
      reason: "Requested permission exceeded delegation constraints.",
      anchorReceiptRefs: ["receipt:permission:002"],
      lineageRefs: ["lineage:permission:002", "lineage:delegation:002"],
      transitionedAtUtc: "2026-03-12T09:05:00Z",
    }],
    readOnly: true,
  }],
]);

const activationSummaries: AuthorityActivationSummaryContract[] = [
  {
    activationId: "activation-001",
    requestingAuthorityRef: "actor-governance-steward",
    agentId: "agent-omega",
    tenantId: "tenant-keon",
    delegationGrantId: "delegation-grant-001",
    permissionGrantId: "permission-grant-001",
    governanceBindingRef: "policy.collective.activation",
    canonicalStatus: "Eligible",
    status: "Eligible",
    correlationId: "corr-activation-001",
    anchorReceiptRefs: ["receipt:activation:001"],
    lineageRefs: ["lineage:activation:001", "lineage:permission:001", "lineage:delegation:001"],
    requestedAtUtc: "2026-03-17T09:10:00Z",
    effectiveFromUtc: "2026-03-17T09:15:00Z",
    expiresAtUtc: "2026-03-20T00:00:00Z",
    badges: ["read-only", "receipt-anchored", "lineage-preserved", "activation-record"],
    readOnly: true,
    receiptAnchored: true,
  },
  {
    activationId: "activation-002",
    requestingAuthorityRef: "actor-governance-steward",
    agentId: "agent-sandbox",
    tenantId: "tenant-keon",
    delegationGrantId: "delegation-grant-002",
    permissionGrantId: "permission-grant-002",
    governanceBindingRef: "policy.collective.activation",
    canonicalStatus: "Revoked",
    status: "Revoked",
    correlationId: "corr-activation-002",
    anchorReceiptRefs: ["receipt:activation:002"],
    lineageRefs: ["lineage:activation:002", "lineage:permission:002", "lineage:delegation:002"],
    requestedAtUtc: "2026-03-12T10:10:00Z",
    effectiveFromUtc: "2026-03-12T10:15:00Z",
    expiresAtUtc: "2026-03-18T00:00:00Z",
    badges: ["read-only", "receipt-anchored", "lineage-preserved", "activation-record"],
    readOnly: true,
    receiptAnchored: true,
  },
];

const activationDetails = new Map<string, AuthorityActivationDetailContract>([
  ["activation-001", {
    summary: activationSummaries[0],
    agentEntityId: "entity-agent-omega",
    domainScope: "collective.reform",
    policyScope: "policy.collective.activation",
    policyVersion: "3.1.0",
    authorityClass: "CollectiveAuthority",
    effectClass: "ReformObservation",
    actionCategories: ["read.reform"],
    capabilityCategories: ["observe.reform"],
    constraintStatements: ["Activation constrained by permission", "Permission constrained by delegation"],
    permittedAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.reform",
      policyScope: "policy.collective.permission",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "ReformObservation",
      actionCategories: ["read.reform"],
      capabilityCategories: ["observe.reform"],
    },
    delegatedAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.reform",
      policyScope: "policy.collective.delegation",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "ReformObservation",
    },
    disposition: {
      dispositionId: "activation-disposition-001",
      activationId: "activation-001",
      kind: "EligibilityConfirmed",
      reasonCode: "GovernanceEligibilityConfirmed",
      actorId: "actor-governance-steward",
      governanceBindingRef: "policy.collective.activation",
      rationale: "The activation remains within the permitted categories and narrowed delegation scope.",
      correlationId: "corr-activation-001",
      anchorReceiptRefs: ["receipt:activation:001"],
      lineageRefs: ["lineage:activation:001", "lineage:permission:001", "lineage:delegation:001"],
      recordedAtUtc: "2026-03-17T09:12:00Z",
    },
    termination: null,
  }],
  ["activation-002", {
    summary: activationSummaries[1],
    agentEntityId: null,
    domainScope: "collective.audit",
    policyScope: "policy.collective.activation",
    policyVersion: "3.1.0",
    authorityClass: "CollectiveAuthority",
    effectClass: "AuditObservation",
    actionCategories: ["read.audit"],
    capabilityCategories: ["observe.audit"],
    constraintStatements: ["Revoked after upstream permission rejection."],
    permittedAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.audit",
      policyScope: "policy.collective.permission",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "AuditObservation",
      actionCategories: ["read.audit"],
      capabilityCategories: ["observe.audit"],
    },
    delegatedAuthorityScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.audit",
      policyScope: "policy.collective.delegation",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "AuditObservation",
    },
    disposition: {
      dispositionId: "activation-disposition-002",
      activationId: "activation-002",
      kind: "Revoked",
      reasonCode: "GovernanceRevoked",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.activation",
      rationale: "Activation revoked because the upstream permission chain failed review.",
      correlationId: "corr-activation-002",
      anchorReceiptRefs: ["receipt:activation:002", "receipt:permission:002"],
      lineageRefs: ["lineage:activation:002", "lineage:permission:002", "lineage:delegation:002"],
      recordedAtUtc: "2026-03-15T14:10:00Z",
    },
    termination: {
      terminationId: "activation-termination-002",
      activationId: "activation-002",
      terminalStatus: "Revoked",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.activation",
      reason: "Revoked after governance review invalidated the authority chain.",
      correlationId: "corr-activation-002",
      anchorReceiptRefs: ["receipt:activation-termination:002"],
      lineageRefs: ["lineage:activation:002", "lineage:termination:002"],
      recordedAtUtc: "2026-03-15T14:12:00Z",
    },
  }],
]);

const activationHistories = new Map<string, AuthorityActivationHistoryContract>([
  ["activation-001", {
    activationId: "activation-001",
    delegationGrantId: "delegation-grant-001",
    permissionGrantId: "permission-grant-001",
    governanceBindingRef: "policy.collective.activation",
    correlationId: "corr-activation-001",
    canonicalStatus: "Eligible",
    history: [{
      activationId: "activation-001",
      status: "Pending",
      requestedAtUtc: "2026-03-17T09:10:00Z",
      effectiveFromUtc: "2026-03-17T09:15:00Z",
      expiresAtUtc: "2026-03-20T00:00:00Z",
      dispositionKind: "EligibilityDenied",
      reasonCode: "GovernanceReviewRequested",
      rationale: "Initial request entered governance review.",
      actorId: "actor-governance-steward",
      transitionId: "activation-transition-001-a",
      fromStatus: "Draft",
      toStatus: "Pending",
      reason: "Submitted for review.",
      anchorReceiptRefs: ["receipt:activation:001"],
      lineageRefs: ["lineage:activation:001"],
      recordedAtUtc: "2026-03-17T09:10:00Z",
    }, {
      activationId: "activation-001",
      status: "Eligible",
      requestedAtUtc: "2026-03-17T09:10:00Z",
      effectiveFromUtc: "2026-03-17T09:15:00Z",
      expiresAtUtc: "2026-03-20T00:00:00Z",
      dispositionKind: "EligibilityConfirmed",
      reasonCode: "GovernanceEligibilityConfirmed",
      rationale: "Eligibility confirmed within narrowed scope.",
      actorId: "actor-governance-steward",
      transitionId: "activation-transition-001-b",
      fromStatus: "Pending",
      toStatus: "Eligible",
      reason: "Confirmed.",
      anchorReceiptRefs: ["receipt:activation:001"],
      lineageRefs: ["lineage:activation:001", "lineage:permission:001"],
      recordedAtUtc: "2026-03-17T09:12:00Z",
    }],
    readOnly: true,
  }],
  ["activation-002", {
    activationId: "activation-002",
    delegationGrantId: "delegation-grant-002",
    permissionGrantId: "permission-grant-002",
    governanceBindingRef: "policy.collective.activation",
    correlationId: "corr-activation-002",
    canonicalStatus: "Revoked",
    history: [{
      activationId: "activation-002",
      status: "Eligible",
      requestedAtUtc: "2026-03-12T10:10:00Z",
      effectiveFromUtc: "2026-03-12T10:15:00Z",
      expiresAtUtc: "2026-03-18T00:00:00Z",
      dispositionKind: "EligibilityConfirmed",
      reasonCode: "GovernanceEligibilityConfirmed",
      rationale: "Initially confirmed as eligible.",
      actorId: "actor-governance-steward",
      transitionId: "activation-transition-002-a",
      fromStatus: "Pending",
      toStatus: "Eligible",
      reason: "Confirmed.",
      anchorReceiptRefs: ["receipt:activation:002"],
      lineageRefs: ["lineage:activation:002"],
      recordedAtUtc: "2026-03-12T10:20:00Z",
    }, {
      activationId: "activation-002",
      status: "Revoked",
      requestedAtUtc: "2026-03-12T10:10:00Z",
      effectiveFromUtc: "2026-03-12T10:15:00Z",
      expiresAtUtc: "2026-03-18T00:00:00Z",
      dispositionKind: "Revoked",
      reasonCode: "GovernanceRevoked",
      rationale: "Revoked after the upstream permission chain failed review.",
      actorId: "actor-constitutional-review",
      transitionId: "activation-transition-002-b",
      fromStatus: "Eligible",
      toStatus: "Revoked",
      reason: "Revoked.",
      anchorReceiptRefs: ["receipt:activation-termination:002"],
      lineageRefs: ["lineage:activation:002", "lineage:termination:002"],
      recordedAtUtc: "2026-03-15T14:12:00Z",
    }],
    readOnly: true,
  }],
]);

const activationLineages = new Map<string, AuthorityActivationLineageContract>([
  ["activation-001", {
    activationId: "activation-001",
    delegationGrantId: "delegation-grant-001",
    permissionGrantId: "permission-grant-001",
    governanceBindingRef: "policy.collective.activation",
    correlationId: "corr-activation-001",
    lineageRefs: ["lineage:activation:001", "lineage:permission:001", "lineage:delegation:001"],
    anchorReceiptRefs: ["receipt:activation:001"],
    canonicalStatus: "Eligible",
    history: [{
      transitionId: "activation-transition-001-a",
      activationId: "activation-001",
      fromStatus: "Draft",
      toStatus: "Pending",
      actorId: "actor-governance-steward",
      governanceBindingRef: "policy.collective.activation",
      reasonCode: "GovernanceReviewRequested",
      reason: "Submitted for review.",
      anchorReceiptRefs: ["receipt:activation:001"],
      lineageRefs: ["lineage:activation:001"],
      transitionedAtUtc: "2026-03-17T09:10:00Z",
    }, {
      transitionId: "activation-transition-001-b",
      activationId: "activation-001",
      fromStatus: "Pending",
      toStatus: "Eligible",
      actorId: "actor-governance-steward",
      governanceBindingRef: "policy.collective.activation",
      reasonCode: "GovernanceEligibilityConfirmed",
      reason: "Confirmed.",
      anchorReceiptRefs: ["receipt:activation:001"],
      lineageRefs: ["lineage:activation:001", "lineage:permission:001"],
      transitionedAtUtc: "2026-03-17T09:12:00Z",
    }],
    readOnly: true,
  }],
  ["activation-002", {
    activationId: "activation-002",
    delegationGrantId: "delegation-grant-002",
    permissionGrantId: "permission-grant-002",
    governanceBindingRef: "policy.collective.activation",
    correlationId: "corr-activation-002",
    lineageRefs: ["lineage:activation:002", "lineage:permission:002", "lineage:delegation:002"],
    anchorReceiptRefs: ["receipt:activation:002"],
    canonicalStatus: "Revoked",
    history: [{
      transitionId: "activation-transition-002-b",
      activationId: "activation-002",
      fromStatus: "Eligible",
      toStatus: "Revoked",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.activation",
      reasonCode: "GovernanceRevoked",
      reason: "Revoked.",
      anchorReceiptRefs: ["receipt:activation-termination:002"],
      lineageRefs: ["lineage:activation:002", "lineage:termination:002"],
      transitionedAtUtc: "2026-03-15T14:12:00Z",
    }],
    readOnly: true,
  }],
]);

const preparedEffectSummaries: PreparedEffectRequestListItemContract[] = [
  {
    preparedRequestId: "prepared-effect-001",
    tenantId: "tenant-keon",
    actorId: "actor-governance-steward",
    agentId: "agent-omega",
    governanceBindingRef: "policy.collective.prepared-effect",
    delegationGrantId: "delegation-grant-001",
    permissionGrantId: "permission-grant-001",
    activationId: "activation-001",
    status: "Materialized",
    dispositionKind: "Materialized",
    reasonCode: "PreparationRecorded",
    domainScope: "collective.reform",
    authorityClass: "CollectiveAuthority",
    effectClass: "ReformObservation",
    actionCategory: "read.reform",
    capabilityCategory: "observe.reform",
    targetClass: "reform.artifact",
    preparedAtUtc: "2026-03-17T09:20:00Z",
    expiresAtUtc: "2026-03-18T09:20:00Z",
    anchorReceiptRefs: ["receipt:prepared-effect:001", "receipt:activation:001"],
    lineageRefs: ["lineage:prepared-effect:001", "lineage:activation:001", "lineage:permission:001"],
    badges: ["read-only", "preparation-only", "inert", "lineage-preserved"],
    readOnly: true,
    preparationOnly: true,
  },
  {
    preparedRequestId: "prepared-effect-002",
    tenantId: "tenant-keon",
    actorId: "actor-constitutional-review",
    agentId: "agent-sandbox",
    governanceBindingRef: "policy.collective.prepared-effect",
    delegationGrantId: "delegation-grant-002",
    permissionGrantId: "permission-grant-002",
    activationId: "activation-002",
    status: "Invalidated",
    dispositionKind: "Invalidated",
    reasonCode: "PreparationInvalidated",
    domainScope: "collective.audit",
    authorityClass: "CollectiveAuthority",
    effectClass: "AuditObservation",
    actionCategory: "read.audit",
    capabilityCategory: "observe.audit",
    targetClass: "audit.record",
    preparedAtUtc: "2026-03-12T10:25:00Z",
    expiresAtUtc: "2026-03-13T10:25:00Z",
    anchorReceiptRefs: ["receipt:prepared-effect:002", "receipt:activation:002"],
    lineageRefs: ["lineage:prepared-effect:002", "lineage:activation:002", "lineage:permission:002"],
    badges: ["read-only", "preparation-only", "inert", "lineage-preserved"],
    readOnly: true,
    preparationOnly: true,
  },
];

const preparedEffectDetails = new Map<string, PreparedEffectRequestDetailContract>([
  ["prepared-effect-001", {
    preparedRequestId: "prepared-effect-001",
    tenantId: "tenant-keon",
    actorId: "actor-governance-steward",
    agentId: "agent-omega",
    governanceBindingRef: "policy.collective.prepared-effect",
    correlationId: "corr-prepared-effect-001",
    delegationGrantId: "delegation-grant-001",
    permissionGrantId: "permission-grant-001",
    activationId: "activation-001",
    selectedBranchId: "branch-001",
    collapseId: "collapse-001",
    reviewId: "review-001",
    heatProfileId: "heat-profile-001",
    status: "Materialized",
    domainScope: "collective.reform",
    authorityClass: "CollectiveAuthority",
    effectClass: "ReformObservation",
    actionCategory: "read.reform",
    capabilityCategory: "observe.reform",
    targetClass: "reform.artifact",
    inheritedTargetClass: "reform",
    activatedScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.reform",
      policyScope: "policy.collective.activation",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "ReformObservation",
      actionCategories: ["read.reform"],
      capabilityCategories: ["observe.reform"],
    },
    constraintStatements: ["NarrowingOnly=true", "ExecutionAuthorized=false", "PreparationOnly=true"],
    disposition: {
      dispositionId: "prepared-disposition-001",
      preparedRequestId: "prepared-effect-001",
      kind: "Materialized",
      reasonCode: "PreparationRecorded",
      actorId: "actor-governance-steward",
      governanceBindingRef: "policy.collective.prepared-effect",
      rationale: "Prepared effect recorded as inert material for downstream observation only.",
      correlationId: "corr-prepared-effect-001",
      anchorReceiptRefs: ["receipt:prepared-effect:001"],
      lineageRefs: ["lineage:prepared-effect:001", "lineage:activation:001"],
      recordedAtUtc: "2026-03-17T09:22:00Z",
    },
    terminal: null,
    preparedAtUtc: "2026-03-17T09:20:00Z",
    expiresAtUtc: "2026-03-18T09:20:00Z",
    anchorReceiptRefs: ["receipt:prepared-effect:001", "receipt:activation:001"],
    lineageRefs: ["lineage:prepared-effect:001", "lineage:activation:001", "lineage:permission:001"],
    badges: ["read-only", "preparation-only", "inert", "lineage-preserved"],
    readOnly: true,
    preparationOnly: true,
  }],
  ["prepared-effect-002", {
    preparedRequestId: "prepared-effect-002",
    tenantId: "tenant-keon",
    actorId: "actor-constitutional-review",
    agentId: "agent-sandbox",
    governanceBindingRef: "policy.collective.prepared-effect",
    correlationId: "corr-prepared-effect-002",
    delegationGrantId: "delegation-grant-002",
    permissionGrantId: "permission-grant-002",
    activationId: "activation-002",
    selectedBranchId: "branch-002",
    collapseId: "collapse-002",
    reviewId: "review-002",
    heatProfileId: "heat-profile-002",
    status: "Invalidated",
    domainScope: "collective.audit",
    authorityClass: "CollectiveAuthority",
    effectClass: "AuditObservation",
    actionCategory: "read.audit",
    capabilityCategory: "observe.audit",
    targetClass: "audit.record",
    inheritedTargetClass: "audit",
    activatedScope: {
      tenantId: "tenant-keon",
      domainScope: "collective.audit",
      policyScope: "policy.collective.activation",
      policyVersion: "3.1.0",
      authorityClass: "CollectiveAuthority",
      effectClass: "AuditObservation",
      actionCategories: ["read.audit"],
      capabilityCategories: ["observe.audit"],
    },
    constraintStatements: ["Invalidated because upstream activation was revoked."],
    disposition: {
      dispositionId: "prepared-disposition-002",
      preparedRequestId: "prepared-effect-002",
      kind: "Invalidated",
      reasonCode: "PreparationInvalidated",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.prepared-effect",
      rationale: "The prepared effect remains inert and was invalidated due to upstream authority failure.",
      correlationId: "corr-prepared-effect-002",
      anchorReceiptRefs: ["receipt:prepared-effect:002", "receipt:activation-termination:002"],
      lineageRefs: ["lineage:prepared-effect:002", "lineage:activation:002"],
      recordedAtUtc: "2026-03-15T14:15:00Z",
    },
    terminal: {
      terminalId: "prepared-terminal-002",
      preparedRequestId: "prepared-effect-002",
      terminalStatus: "Invalidated",
      actorId: "actor-constitutional-review",
      governanceBindingRef: "policy.collective.prepared-effect",
      reason: "Invalidated after upstream activation revocation.",
      correlationId: "corr-prepared-effect-002",
      anchorReceiptRefs: ["receipt:prepared-effect-terminal:002"],
      lineageRefs: ["lineage:prepared-effect:002", "lineage:termination:002"],
      recordedAtUtc: "2026-03-15T14:16:00Z",
    },
    preparedAtUtc: "2026-03-12T10:25:00Z",
    expiresAtUtc: "2026-03-13T10:25:00Z",
    anchorReceiptRefs: ["receipt:prepared-effect:002", "receipt:activation:002"],
    lineageRefs: ["lineage:prepared-effect:002", "lineage:activation:002", "lineage:permission:002"],
    badges: ["read-only", "preparation-only", "inert", "lineage-preserved"],
    readOnly: true,
    preparationOnly: true,
  }],
]);

const preparedEffectLineages = new Map<string, PreparedEffectLineageContract>([
  ["prepared-effect-001", {
    preparedRequestId: "prepared-effect-001",
    delegationGrantId: "delegation-grant-001",
    permissionGrantId: "permission-grant-001",
    activationId: "activation-001",
    governanceBindingRef: "policy.collective.prepared-effect",
    correlationId: "corr-prepared-effect-001",
    selectedBranchId: "branch-001",
    collapseId: "collapse-001",
    reviewId: "review-001",
    heatProfileId: "heat-profile-001",
    lineageRefs: ["lineage:prepared-effect:001", "lineage:activation:001", "lineage:permission:001"],
    anchorReceiptRefs: ["receipt:prepared-effect:001", "receipt:activation:001"],
    status: "Materialized",
    badges: ["read-only", "preparation-only", "inert", "lineage-preserved"],
    readOnly: true,
    preparationOnly: true,
  }],
  ["prepared-effect-002", {
    preparedRequestId: "prepared-effect-002",
    delegationGrantId: "delegation-grant-002",
    permissionGrantId: "permission-grant-002",
    activationId: "activation-002",
    governanceBindingRef: "policy.collective.prepared-effect",
    correlationId: "corr-prepared-effect-002",
    selectedBranchId: "branch-002",
    collapseId: "collapse-002",
    reviewId: "review-002",
    heatProfileId: "heat-profile-002",
    lineageRefs: ["lineage:prepared-effect:002", "lineage:activation:002", "lineage:permission:002"],
    anchorReceiptRefs: ["receipt:prepared-effect:002", "receipt:activation:002"],
    status: "Invalidated",
    badges: ["read-only", "preparation-only", "inert", "lineage-preserved"],
    readOnly: true,
    preparationOnly: true,
  }],
]);

const proposalToArtifactId = new Map<string, string>([
  ["proposal-signal-weighting-v2", "reform-001"],
  ["proposal-threshold-policy", "reform-002"],
]);

export function buildMockReformAdoptionListResponse(filters: ReformAdoptionFilterState = {}): ListReformAdoptionDecisionsResponse {
  return {
    items: adoptionDecisions.filter((decision) => {
      if (filters.decisionId && decision.decisionId !== filters.decisionId) return false;
      if (filters.proposalId && decision.proposalId !== filters.proposalId) return false;
      if (filters.legitimacyAssessmentId && decision.legitimacyAssessmentId !== filters.legitimacyAssessmentId) return false;
      if (filters.anchorEpochId && decision.anchorEpochId !== filters.anchorEpochId) return false;
      if (filters.disposition && decision.disposition !== filters.disposition) return false;
      if (filters.artifactId && proposalToArtifactId.get(decision.proposalId) !== filters.artifactId) return false;
      return true;
    }),
  };
}

export function getMockReformAdoptionDetailResponse(decisionId: string): GetReformAdoptionDecisionDetailResponse | null {
  const decision = adoptionDecisions.find((item) => item.decisionId === decisionId);
  return decision ? { decision, mutationReceiptGroups: mutationReceiptsByDecision.get(decisionId) ?? [] } : null;
}

export function buildMockDelegatedAuthorityListResponse(): ListDelegatedAuthorityGrantsResponse {
  return { items: delegationSummaries };
}

export function getMockDelegatedAuthorityDetailResponse(grantId: string): GetDelegatedAuthorityGrantDetailResponse | null {
  const grant = delegationDetails.get(grantId);
  return grant ? { grant } : null;
}

export function getMockDelegatedAuthorityLineageResponse(grantId: string): GetDelegatedAuthorityLineageResponse | null {
  const lineage = delegationLineages.get(grantId);
  return lineage ? { lineage } : null;
}

export function buildMockAgentPermissionListResponse(): ListAgentPermissionGrantsResponse {
  return { items: permissionSummaries };
}

export function getMockAgentPermissionDetailResponse(grantId: string): GetAgentPermissionGrantDetailResponse | null {
  const grant = permissionDetails.get(grantId);
  return grant ? { grant } : null;
}

export function getMockAgentPermissionLineageResponse(grantId: string): GetAgentPermissionLineageResponse | null {
  const lineage = permissionLineages.get(grantId);
  return lineage ? { lineage } : null;
}

export function buildMockAuthorityActivationListResponse(): ListAuthorityActivationsResponse {
  return { items: activationSummaries };
}

export function getMockAuthorityActivationDetailResponse(activationId: string): GetAuthorityActivationDetailResponse | null {
  const activation = activationDetails.get(activationId);
  return activation ? { activation } : null;
}

export function getMockAuthorityActivationHistoryResponse(activationId: string): GetAuthorityActivationHistoryResponse | null {
  const history = activationHistories.get(activationId);
  return history ? { history } : null;
}

export function getMockAuthorityActivationLineageResponse(activationId: string): GetAuthorityActivationLineageResponse | null {
  const lineage = activationLineages.get(activationId);
  return lineage ? { lineage } : null;
}

export function buildMockPreparedEffectListResponse(): ListPreparedEffectRequestsResponse {
  return { items: preparedEffectSummaries };
}

export function getMockPreparedEffectDetailResponse(preparedRequestId: string): GetPreparedEffectRequestDetailResponse | null {
  const preparedEffect = preparedEffectDetails.get(preparedRequestId);
  return preparedEffect ? { preparedEffect } : null;
}

export function getMockPreparedEffectLineageResponse(preparedRequestId: string): GetPreparedEffectLineageResponse | null {
  const lineage = preparedEffectLineages.get(preparedRequestId);
  return lineage ? { lineage } : null;
}
